### ISSUE TITLE
Implement error handling for case where there is no raster data in boundary

### ISSUE THREAD

**Issue by nicolepaul** [GEMScienceTools/spatial-disaggregation#5]
There are cases where an administrative boundary might be so small that it is either close to the target resolution or potentially smaller. For example, Jamal has reported this case for the small islands off-shore of Portugal. At present, the code fails and errors at the point of masking the raster grid to the boundary division.

It would be better for these cases if we threw a warning to the user and skipped disaggregation of those boundaries, as the resolution is already quite small in those cases.

**Comment by jamaldabbeek** [comment]
Thanks Nicole, here are files for this case
[Portugal_test.zip](https://github.com/GEMScienceTools/spatial-disaggregation/files/6364256/Portugal_test.zip)
